spring.application.name=final-project
# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/project
spring.datasource.username=postgres
spring.datasource.password=683683
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# --- Logging ---
logging.level.com.example.finalproject=DEBUG
logging.file.name=logs/app.log

# --- Telegram Bot (для новой библиотеки) ---
telegram.bot.token=8809494030:AAHR1f5PI6I6SlazT2IQxrskib8DaSLU18Q
telegram.bot.username=project683_bot


jwt.accessTokenExpiration=3600000
jwt.refreshTokenExpiration=86400000
jwt.secret=yourSecretKeyForJwtTokenGenerationMustBeAtLeast256BitsLong

JWT_ACCESS_COOKIE_NAME=access_token
JWT_REFRESH_COOKIE_NAME=refresh_token